# 服务监听端口
server:
  port: 8040

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # 禁止注册到eureka中心, 当前这个应用就是Eureka Server，所以不需要把自己注册
    fetch-registry: false # 禁止从中心获取文件, 这是一个单点的Eureka Server，
    # 不需要同步其他Eureka Server节点的数据，设为false
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
