server:
  port: 8045
spring:
  application:
    name: service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8040/eureka
    register-with-eureka: true
    fetch-registry: true
zuul:
  routes:
    api-a:
      serviceId: service-provider
      path: /api/**
    api-b:
      serviceId: server-c
      path: /api-c/**
#    api-c:
#      serviceId: application-client
#      path: /rest/**
