server:
  port: 8043
spring:
  application:
    name: service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8040/eureka
    register-with-eureka: true
    fetch-registry: true
zuul:
  routes:
    api-a:
      serviceId: service-a
      path: /api-a/**
    api-b:
      serviceId: service-b
      path: /api-b/**
    api-c:
      serviceId: application-client
      path: /rest/**
